---
minimum_pre_commit_version: 4.5.1
exclude: ^(docs|tests)

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.13.9
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md

# Checking packaging
- repo: https://github.com/regebro/pyroma
  rev: 5.0.1
  hooks:
  - id: pyroma

# Ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.6
  hooks:
  - id: ruff-check
    args:
    - --fix
  - id: ruff-format

# Ty (Experimental)
- repo: local
  hooks:
  - id: ty
    name: ty check
    entry: ty check .
    language: system
    pass_filenames: false
    always_run: true
