---
name: build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  # Build daily at 6:29am...
  - cron: '29 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: pip install uv
    - name: Static Analysis
      run: |
        uv run pre-commit run --all-files
    - name: Build
      run: uv build
    - name: Compile Documentation
      run: uv run sphinx-build -b html docs _readthedocs/html/
