---

# Publish the application to PyPI
name: publish

on:
  push:
    tags:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install build dependencies
      run: pip install uv
    - name: Build
      run: |
        uv version $GITHUB_REF_SLUG
        uv build
    - name: Store the distribution
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distribution
        path: dist/

  publish:
    name: Publish to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/im-squonk2-client
    permissions:
      id-token: write
    steps:
    - name: Download distribution
      uses: actions/download-artifact@v6
      with:
        name: python-package-distribution
        path: dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
